version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cacamba_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cacamba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cacamba"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dbdata:
